name: Automated Playok Scraper

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # Explicitní povolení zápisu přímo v kódu
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install axios cheerio

      - name: Run scraper
        run: node scraper.js

      - name: Commit and push changes
        run: |
          git config --global user.name "Meijin Bot"
          git config --global user.email "bot@meijin.com"
          git add data.json
          git commit -m "Automated update: New tournament data" || exit 0
          git push
